require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/resumes', type: :request do
  let(:user) { create_user(role: 'admin') }
  let(:admin) do
    Admin.find_or_create_by!(
      email: user.email,
      uid: user.google_uid,
      full_name: "#{user.first_name} #{user.last_name}"
    )
  end

  before do
    sign_in admin
  end

  let(:valid_attributes) do
    {
      user_id: user.id,
      file: fixture_file_upload('spec/fixtures/test.pdf', 'application/pdf')
    }
  end

  let(:invalid_attributes) do
    {
      file: nil # File is required for resumes
    }
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Resume.create! valid_attributes
      get resumes_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      Resume.create! valid_attributes
      get user_resume_url(user)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_user_resume_url(user)
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      resume = Resume.create! valid_attributes
      get edit_resume_url(resume)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Resume' do
        expect do
          post user_resume_url(user), params: { resume: valid_attributes }
        end.to change(Resume, :count).by(1)
      end

      it 'redirects to the created resume' do
        post user_resume_url(user), params: { resume: valid_attributes }
        expect(response).to redirect_to(user_path(user))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Resume' do
        expect do
          post user_resume_url(user), params: { resume: invalid_attributes }
        end.not_to change(Resume, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post user_resume_url(user), params: { resume: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe 'PATCH /update' do
    let!(:resume) { Resume.create!(user: user, file: fixture_file_upload('spec/fixtures/test.pdf', 'application/pdf')) }

    context 'with valid parameters' do
      let(:new_attributes) do
        { file: fixture_file_upload('spec/fixtures/test.pdf', 'application/pdf') }
      end

      it 'updates the requested resume' do
        patch user_resume_url(user), params: { resume: new_attributes }
        resume.reload
        expect(response).to redirect_to(user_path(user))
      end

      it 'redirects to the user' do
        patch user_resume_url(user), params: { resume: new_attributes }
        resume.reload
        expect(response).to redirect_to(user_path(user))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        # Create a new resume with a valid file
        Resume.create!(user: user, file: fixture_file_upload('spec/fixtures/test.pdf', 'application/pdf'))

        # Attempt to update the resume with invalid metadata (gpa out of range)
        patch user_resume_url(user), params: { resume: { gpa: 10.0 } }

        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe 'DELETE /destroy' do
    let!(:resume) { Resume.create!(user: user, file: fixture_file_upload('spec/fixtures/test.pdf', 'application/pdf')) }

    it 'destroys the requested resume' do
      expect do
        delete user_resume_url(user)
      end.to change(Resume, :count).by(-1)
    end

    it 'redirects to the user page' do
      delete user_resume_url(user)
      expect(response).to redirect_to(user_path(user))
    end

    it 'allows admins to delete any resume' do
      other_user = create_user(role: 'member', uid: 'other_uid')
      other_resume = Resume.create!(user: other_user,
                                    file: fixture_file_upload('spec/fixtures/test.pdf', 'application/pdf'))
      sign_in admin

      # Use the nested route which sets @user properly
      delete user_resume_url(other_user)

      # Admins can delete any resume
      expect { other_resume.reload }.to raise_error(ActiveRecord::RecordNotFound)
      expect(response).to redirect_to(user_path(other_user))
      expect(flash[:notice]).to include('Resume was successfully deleted')
    end
  end

  describe 'authorization and edge cases' do
    it 'handles resume not found gracefully' do
      get resume_url(id: 99_999)
      expect(response).to redirect_to(resumes_path)
      expect(flash[:alert]).to include('Resume not found')
    end

    it 'prevents creating duplicate resume for same user' do
      Resume.create!(user: user, file: fixture_file_upload('spec/fixtures/test.pdf', 'application/pdf'))

      get new_user_resume_url(user)
      expect(response).to redirect_to(user_path(user))
      expect(flash[:alert]).to include('User already has a resume')
    end

    it 'allows editing own resume' do
      resume = Resume.create!(user: user, file: fixture_file_upload('spec/fixtures/test.pdf', 'application/pdf'))

      get edit_resume_url(resume)
      expect(response).to have_http_status(:success)
    end

    it 'allows admins to edit any resume' do
      other_user = create_user(role: 'member', uid: 'other_uid')
      other_resume = Resume.create!(user: other_user,
                                    file: fixture_file_upload('spec/fixtures/test.pdf', 'application/pdf'))
      sign_in admin

      # Admins can edit any resume
      get edit_resume_url(other_resume)
      expect(response).to have_http_status(:success)
    end
  end
end
