require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/resumes', type: :request do
  let(:user) { User.create!(email: 'test@example.com', google_uid: '12345') }

  let(:valid_attributes) do
    {
      user_id: user.id,
      file: fixture_file_upload('spec/fixtures/test.pdf', 'application/pdf')
    }
  end

  let(:invalid_attributes) do
    {
      file: nil # File is required for resumes
    }
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Resume.create! valid_attributes
      get resumes_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      Resume.create! valid_attributes
      get user_resume_url(user)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_user_resume_url(user)
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      resume = Resume.create! valid_attributes
      get edit_resume_url(resume)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Resume' do
        expect do
          post user_resume_url(user), params: { resume: valid_attributes }
        end.to change(Resume, :count).by(1)
      end

      it 'redirects to the created resume' do
        post user_resume_url(user), params: { resume: valid_attributes }
        expect(response).to redirect_to(user_path(user))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Resume' do
        expect do
          post user_resume_url(user), params: { resume: invalid_attributes }
        end.to change(Resume, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post user_resume_url(user), params: { resume: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    let!(:resume) { Resume.create!(user: user, file: fixture_file_upload('spec/fixtures/test.pdf', 'application/pdf')) }

    context 'with valid parameters' do
      let(:new_attributes) do
        { file: fixture_file_upload('spec/fixtures/test.pdf', 'application/pdf') }
      end

      it 'updates the requested resume' do
        patch user_resume_url(user), params: { resume: new_attributes }
        resume.reload
        expect(response).to redirect_to(user_path(user))
      end

      it 'redirects to the user' do
        patch user_resume_url(user), params: { resume: new_attributes }
        resume.reload
        expect(response).to redirect_to(user_path(user))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        # Create a new resume with a valid file
        Resume.create!(user: user, file: fixture_file_upload('spec/fixtures/test.pdf', 'application/pdf'))

        # Attempt to update the resume with an invalid file (nil)
        patch user_resume_url(user), params: { resume: { file: nil } }

        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    let!(:resume) { Resume.create!(user: user, file: fixture_file_upload('spec/fixtures/test.pdf', 'application/pdf')) }

    it 'destroys the requested resume' do
      expect do
        delete user_resume_url(user)
      end.to change(Resume, :count).by(-1)
    end

    it 'redirects to the user page' do
      delete user_resume_url(user)
      expect(response).to redirect_to(user_path(user))
    end
  end
end
