require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/role_applications', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # RoleApplication. As you add validations to RoleApplication, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      RoleApplication.create! valid_attributes
      get role_applications_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      role_application = RoleApplication.create! valid_attributes
      get role_application_url(role_application)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_role_application_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      role_application = RoleApplication.create! valid_attributes
      get edit_role_application_url(role_application)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new RoleApplication' do
        expect do
          post role_applications_url, params: { role_application: valid_attributes }
        end.to change(RoleApplication, :count).by(1)
      end

      it 'redirects to the created role_application' do
        post role_applications_url, params: { role_application: valid_attributes }
        expect(response).to redirect_to(role_application_url(RoleApplication.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new RoleApplication' do
        expect do
          post role_applications_url, params: { role_application: invalid_attributes }
        end.to change(RoleApplication, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post role_applications_url, params: { role_application: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested role_application' do
        role_application = RoleApplication.create! valid_attributes
        patch role_application_url(role_application), params: { role_application: new_attributes }
        role_application.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the role_application' do
        role_application = RoleApplication.create! valid_attributes
        patch role_application_url(role_application), params: { role_application: new_attributes }
        role_application.reload
        expect(response).to redirect_to(role_application_url(role_application))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        role_application = RoleApplication.create! valid_attributes
        patch role_application_url(role_application), params: { role_application: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested role_application' do
      role_application = RoleApplication.create! valid_attributes
      expect do
        delete role_application_url(role_application)
      end.to change(RoleApplication, :count).by(-1)
    end

    it 'redirects to the role_applications list' do
      role_application = RoleApplication.create! valid_attributes
      delete role_application_url(role_application)
      expect(response).to redirect_to(role_applications_url)
    end
  end
end
